[package]
name = "hello-world"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-web = "4.4"
env_logger = "0.10"
log = "0.4"
# scylla = "0.11.1"
scylla = { git = "https://github.com/Lorak-mmk/scylla-rust-driver", branch = "enable-tracing-log" }
